Selection for equivariant tensors, and return Hausdorff distances
lab-cosmo/equisolve pull request #59
Opened 2023-08-08 15:14 UTC by jwa7

- Modifies the `GreedySelector.fit` method to allow for TensorMaps with a single components axis (i.e. equivariants)
- Allows the user to pass either an `int` or `dict` for `n_to_select`. Setting to an int sets a fixed value for every block. Setting to -1 sets to the maximum number of samples/features for each block. Setting to a dict allows explicit control of the number of selection points for each block
- Returns the sorted Haussdorf distances in the `selector.get_select_distance` property.

For instance, one can plot sorted Haussdorf distances for the features of each block as follows:

```python
import matplotlib.pyplot as plt
import numpy as np

import equistore
from equisolve.numpy import feature_selection

tensor = equistore.load("tensor.npz")

# n_to_select = 10  # set num features to 10 for every block
n_to_select = -1  # set to the max for each block
# n_to_select = {  
#     tuple(key.values): len(block.properties) - np.random.randint(0, 2)
#     for key, block in tensor.items()
# }  # control for each block

selector = feature_selection.FPS(n_to_select=n_to_select, initialize="random")
tensor_fps = selector.fit_transform(tensor)

fig, ax = plt.subplots()
for key, block in selector.get_select_distance.items():
    ax.loglog(np.sort(block.values.flatten())[::-1], label=key)

fig.legend()
```

Still to do:

- [x] Update tests

----
:books: Documentation preview :books:: https://equisolve--59.org.readthedocs.build/en/59/

2023-08-09 08:49 UTC, jwa7 commented
> > (NB: Haussdorf is spelled as such in the code (and not Hausdorff) for consistency with the corresponding skmatter methods)
> 
> We will fix this [scikit-learn-contrib/scikit-matter#207](https://github.com/scikit-learn-contrib/scikit-matter/pull/207)

Ok thanks, I will correct the spelling in this PR too.

2023-09-19 11:52 UTC, PicoCentauri commented
What is the status here @jwa7 ? Seems like there some attribute problems?

2023-10-02 11:44 UTC, PicoCentauri requested changes
I got a quick look. Just found a minor typo.

2023-10-02 11:44 UTC, PicoCentauri commented on src/equisolve/numpy/_selection.py
> +        # CHeck that we have only 0 or 1 comoponent axes
```suggestion
        # Check that we have only 0 or 1 comoponent axes
```

2023-10-03 06:07 UTC, PicoCentauri approved these changes
LGTM. Merge when you want and the CI passed.

2023-10-03 06:20 UTC, merged

2023-10-03 08:09 UTC, jwa7 commented
LGTM => looks good to me :handshake: let’s get this merged